#!/usr/bin/env node
// Single source for version-related release operations.
//
// Modes:
//   --check           Assert that package.json.version and src/version.ts are
//                     both pinned to the placeholder. Used by ci.yml on every
//                     PR/push to main so hand-bumps are caught at review time.
//
//   --bake <X.Y.Z>    Rewrite the placeholder in package.json (.version) and
//                     src/version.ts (VERSION literal) to the given SemVer.
//                     Used by release.yml right after the tag is parsed.
//
// Why a node script instead of sed/jq:
//   - sed pattern was tied to one specific quote style; a Biome reformat
//     could silently break it.
//   - We want loud, specific errors: "placeholder not found in src/version.ts"
//     beats "sed succeeded but matched nothing".
//   - --check shares the same parsing logic as --bake (single source of truth).

import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const PKG_PATH = resolve(REPO_ROOT, "package.json");
const VERSION_TS_PATH = resolve(REPO_ROOT, "src/version.ts");
const PLACEHOLDER = "0.0.0-development";

// Reject leading zeros (SemVer 2.0.0 §2). Also reject pre-release / build
// metadata — we currently do not support prerelease tags via this flow.
const STRICT_SEMVER = /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$/;

function readPackageJson() {
	const raw = readFileSync(PKG_PATH, "utf8");
	return { raw, json: JSON.parse(raw) };
}

function readVersionTs() {
	return readFileSync(VERSION_TS_PATH, "utf8");
}

function fail(message) {
	console.error(`[release-version] ${message}`);
	process.exit(1);
}

function check() {
	const { json } = readPackageJson();
	if (json.version !== PLACEHOLDER) {
		fail(
			`package.json "version" must be pinned to "${PLACEHOLDER}", got "${json.version}". See _version_note in package.json — never bump by hand.`,
		);
	}

	const versionTs = readVersionTs();
	const expected = `export const VERSION = "${PLACEHOLDER}";`;
	if (!versionTs.includes(expected)) {
		fail(
			`src/version.ts must contain the literal line:\n  ${expected}\nDo not edit this file by hand — release.yml writes it from the git tag.`,
		);
	}

	console.log(
		`[release-version] OK: package.json and src/version.ts are both pinned to ${PLACEHOLDER}.`,
	);
}

function bake(version) {
	if (!STRICT_SEMVER.test(version)) {
		fail(
			`Version "${version}" is not a valid SemVer (X.Y.Z with no leading zeros, no prerelease, no build metadata).`,
		);
	}

	// Verify the placeholders are still present before mutating. If a previous
	// step already baked (or someone hand-edited), refuse rather than produce
	// a different result than expected.
	check();

	const { json } = readPackageJson();
	json.version = version;
	// Preserve tab indentation and trailing newline (matches what Biome emits).
	writeFileSync(PKG_PATH, `${JSON.stringify(json, null, "\t")}\n`, "utf8");

	const versionTs = readVersionTs();
	const baked = versionTs.replace(
		`export const VERSION = "${PLACEHOLDER}";`,
		`export const VERSION = "${version}";`,
	);
	writeFileSync(VERSION_TS_PATH, baked, "utf8");

	// Post-bake sanity: re-read and confirm. Catches any unforeseen race.
	const { json: postPkg } = readPackageJson();
	const postVersionTs = readVersionTs();
	const expectedLine = `export const VERSION = "${version}";`;
	if (postPkg.version !== version || !postVersionTs.includes(expectedLine)) {
		fail("post-bake verification failed — files are in an inconsistent state.");
	}

	console.log(
		`[release-version] Baked ${version} into package.json and src/version.ts.`,
	);
}

const [mode, ...rest] = process.argv.slice(2);

if (mode === "--check" && rest.length === 0) {
	check();
} else if (mode === "--bake" && rest.length === 1) {
	bake(rest[0]);
} else {
	console.error(
		"usage:\n  node scripts/release-version.mjs --check\n  node scripts/release-version.mjs --bake <X.Y.Z>",
	);
	process.exit(2);
}
